// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using YouGotMailAPI;
using YouGotMailAPI.EmailServices;
using YouGotMailAPI.Models;



#nullable disable

namespace YouGotMailAPI.Database
{
    public partial class MailDBContext : DbContext
    {
        public MailDBContext() {
        }

        public MailDBContext(DbContextOptions<MailDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<UserEmailOptions> Emails { get; set; }
        public virtual DbSet<Mail> Mail { get; set; }



        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) {
            if (!optionsBuilder.IsConfigured) {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer(Secrets.ConnectionString);
            }
        }

        //    protected override void OnModelCreating(ModelBuilder modelBuilder)
        //    {
        //        modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

        //        modelBuilder.Entity<UserEmailOptions>(entity =>
        //        {
        //            entity.Property(e => e.Id).ValueGeneratedNever();
        //        });

        //        OnModelCreatingPartial(modelBuilder);
        //    }

        //    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
        //
    }
}